spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_open_platform?characterEncoding=utf-8&useSSL=false
    username: root
    password: zengchao