spring:
  application:
    name: Api-open-platform
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_open_platform?characterEncoding=utf-8&useSSL=false
    username: root
    password: zengchao
  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    timeout: 20000
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool.max-active: 20
      # 最大阻塞等待时间(负数表示没限制)
      pool.max-wait: -1
      # 连接池中的最大空闲连接
      pool.max-idle: 5
      # 连接池中的最小空闲连接
      pool.min-idle: 0

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)